title: [Skoona's Explorations]
email: [skoona@gmail.com]
description: > # this means to ignore newlines until "baseurl:"
  Avid software developer on all platforms, recent favorites include the
  Raspberry PI, Parallella, Linux, and OS-X.   Most interested in systems programming,
  integration, software engineering methodologies and system architectures.  Currently involved writing
  Ruby Web applications using Ruby on Rails and JRuby.
baseurl: ""
url: https://skoona.github.io 

twitter_username: JamesScottiii
twitter:
  username: jamesscottiii

github_username:  skoona
github:
  username:  skoona

# paginate:     1
author:
  name:       "James Scott, Jr. (a.k.a Skoona)"
  url:        https://keybase.io/skoona


# Build settings
header_pages:
  - about.md
  - contact.md

markdown: kramdown
theme:
# theme: jekyll-theme-cayman-blog

cayman-blog:
  date_format: "%b %-d, %Y"

excerpt_separator: <!--more-->
plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-paginate

github: [metadata]


